### ISSUE TITLE
sql: Scan error on column index

### ISSUE THREAD

**Issue by kenske** [gotify/android#112]
I'm using mysql for the database. I'm seeing this error in the app logs:

```
2020-05-26T04:33:09.653Z ERROR: failed requesting messages
Code(500) Response: {"error":"Internal Server Error","errorCode":500,"errorDescription":"sql: Scan error on column index 6, name \"date\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time; sql: Sc
	at com.github.gotify.api.Api.execute(Api.java:15)
	at com.github.gotify.messages.provider.MessageRequester.loadMore(MessageRequester.java:23)
	at com.github.gotify.messages.provider.MessageFacade.loadMore(MessageFacade.java:34)
	at com.github.gotify.messages.provider.MessageFacade.loadMoreIfNotPresent(MessageFacade.java:43)
	at com.github.gotify.messages.MessagesActivity$SelectApplicationAndUpdateMessages.doInBackground(MessagesActivity.java:606)
	at com.github.gotify.messages.MessagesActivity$SelectApplicationAndUpdateMessages.doInBackground(MessagesActivity.java:595)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by jmattheis** [comment]
Does your mysql connection string include `parseTime=True`
```
gotify:secret@/gotifydb?charset=utf8&parseTime=True&loc=Local
```
https://gotify.net/docs/config#database
