### ISSUE TITLE
Gotify Android client keeps disconnecting

### ISSUE THREAD

**Issue by MnM001** [gotify/android#153]
Hi,

I am running latest gotify docker (2.0.21)
The relevant docker compose section is:

<details><summary>Docker startup command or config file here (please mask sensitive information)</summary><br>

Docker Compose section
```
    gotify:
        image: gotify/server:latest
        container_name: gotify
        hostname: gotify
        volumes:
            - /gotify/config:/app/data
        environment:
            - TZ=Europe/Berlin
        networks:
            - gotify
        ports:
            - 8083:80
        restart: unless-stopped
```
</details>

No reverse proxy - my android mobile connects directly to the Ubuntu server running the Gotify docker.

After a few minutes (cant really say how many because sometimes is 3 minutes sometimes is 10m or more) my android client running on Samsung S20 (latest version installed form the App Store) disconnects. It then reconnects again after about 1m.

<details><summary>Here is the error log I see in the Android Gotify App:</summary><br>
2021-01-26T08:54:48.513Z INFO: Entering LogsActivity<br>
2021-01-26T08:54:46.358Z INFO: Loading more messages for -1<br>
2021-01-26T08:54:46.349Z INFO: Entering MessagesActivity<br>
2021-01-26T08:54:45.943Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)<br>
2021-01-26T08:54:45.934Z ERROR: WebSocket(46): failure  Message: <br>
java.net.SocketException: Software caused connection abort<br>
at java.net.SocketInputStream.socketRead0(Native Method)<br>
at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)<br>
at java.net.SocketInputStream.read(SocketInputStream.java:176)<br>
at java.net.SocketInputStream.read(SocketInputStream.java:144)<br>
at okio.Okio$2.read(Okio.java:140)<br>
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)<br>
at okio.RealBufferedSource.request(RealBufferedSource.java:68)<br>
at okio.RealBufferedSource.require(RealBufferedSource.java:61)<br>
at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)<br>
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)<br>
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)<br>
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)<br>
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)<br>
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)<br>
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)<br>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)<br>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)<br>
at java.lang.Thread.run(Thread.java:923)<br>
2021-01-26T08:44:33.867Z INFO: WebSocket(46): opened<br>
2021-01-26T08:44:33.852Z INFO: WebSocket(46): starting...<br>
2021-01-26T08:44:33.851Z INFO: WebSocket(45): closing existing connection.<br>
</details>

<details><summary>In the Gotify docker I see this:</summary><br>
[GIN] 2021/01/26 - 16:43:35 | 200 |    1.861066ms |   192.168.0.109 | GET      "/message?limit=100&since=0"<br>
[GIN] 2021/01/26 - 16:43:35 | 200 |     287.713µs |   192.168.0.109 | GET      "/application"<br>
[GIN] 2021/01/26 - 16:43:42 | 200 |     532.745µs |   192.168.0.109 | GET      "/message?limit=10"<br>
[GIN] 2021/01/26 - 16:43:56 | 200 |      54.402µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:44:27 | 200 |       74.13µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:44:33 | 200 |     293.584µs |   192.168.0.109 | GET      "/stream?token=XXXXXXXXXXXXXXXXX"<br>
[GIN] 2021/01/26 - 16:44:33 | 200 |     424.421µs |   192.168.0.109 | GET      "/message?limit=10"<br>
[GIN] 2021/01/26 - 16:44:57 | 200 |      53.601µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:45:27 | 200 |      88.217µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:45:57 | 200 |      39.675µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:46:27 | 200 |      44.945µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:46:57 | 200 |      35.877µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:47:27 | 200 |      44.333µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:47:57 | 200 |      65.964µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:48:27 | 200 |      31.709µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:48:58 | 200 |      35.858µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:49:28 | 200 |      34.504µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:49:58 | 200 |      39.365µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:50:28 | 200 |      33.314µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:50:58 | 200 |      29.857µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:51:28 | 200 |       42.43µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:51:58 | 200 |      36.889µs |       127.0.0.1 | GET      "/health"<br>
[GIN] 2021/01/26 - 16:52:28 | 200 |      42.631µs |       127.0.0.1 | GET      "/health"<br>
WebSocket: ReadError read tcp 172.18.0.4:80->192.168.0.109:46576: read: connection reset by peer<br>
</details>

Ubuntu Server running the Gotify docker is 192.168.0.172 (no firewall)
Gotify Docker is 172.18.0.4
Mobile phone running the Gotify Android app is 192.168.0109

I have tried a few things like adding
            - GOTIFY_SERVER_KEEPALIVEPERIODSECONDS=60
            - GOTIFY_SERVER_STREAM_PINGPERIODSECONDS=60
to the docker compose file but it made no difference.

Battery optimization for Gotify app is disabled.

Thanks

**Comment by jmattheis** [comment]
Hey, 

thanks for the detailed report, sadly this is a pretty generic connection error which isn't that easy to debug. On my local network I cannot reproduce your problem.

Could you try manually connecting to the web socket from the local server and maybe another server/pc and see if it disconnects as well?
You could use wscat for this `wscat -P -c "ws://localhost:8080/stream?token=Cvo90l5vqpa4lPF"`(token must be a client token)

**Comment by biggdaniell** [comment]
I have the same issue.
The real problem is that it not reconnecting automatically (I get that message saying it will try again in 20 minutes but it stays that way). I have to logout from the application and login/re-register it to get it to work again.
Also, despite battery optimization/sleeping apps being disabled, I can only get it to work if I allow foreground notifications. Otherwise, as soon as the app is minimized (by pressing the android home button) it's no longer working (no notifications at all - if I open it again I can see the messages, but no notifications).

**Comment by jmattheis** [comment]
@biggdaniell open a new issue with your problem & logs, your issue is probably different.

**Comment by quthla** [comment]
Also having this issue. On 2.0.12 and before I fixed it like this https://github.com/quthla/android/commit/85f1b0282b27c268f870ff7c590d8c616ef9f049

But since I rebased on 2.0.14, this won't work anymore.

**Comment by MnM001** [comment]
OK so I have run the wscat command from another pc on the network - no timeouts detected.
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
< Received ping
etc (been running for 1h so far)

Looks like is something related to the Android app.

If I have the running in the background I get the disconnections.

If the app is open no disconnections - even if the phone is locked. As soon as the app goes into background the disconnections start to happen again.

**Comment by jmattheis** [comment]
How are you accessing gotify from you android app. Via wifi or mobile. Either way, I can reproduce the exact same exception if I disconnect my wifi while having the android app running. Thus, it is most likely some kind of network error that gotify (server & android) cannot control.

**Comment by MnM001** [comment]
I have tried both wifi and 4G - same result.
I have tried closing the app and restarting it while being on the same connection method. Same result.
Given that the application runs OK when opened on the mobile makes me think it has nothing to do with wifi or 4g at all

**Comment by jmattheis** [comment]
Could you check if you have disabled background data use for gotify. see https://www.technipages.com/android-enable-disable-background-data

**Comment by MnM001** [comment]
In my mobile "Allow background data usage" option for Gotify app is set to ON

**Comment by MnM001** [comment]
Looks like quthla managed to sort out the Android disconnect/reconnect issue in his fork here
https://github.com/quthla/android

Is this something you can have a look at, fix and release a new android version in Google Play?

**Comment by jmattheis** [comment]
Sure, if there is a clear explanation why it does fix the problem.

**Comment by quthla** [comment]
The commit fixed the reconnect issue in versions before 2.0.13 but is not needed anymore since @jmattheis fixed the issue upstream. I'm currently also running a version of my work without that particular commit of mine.

Basically I just keep my fork around for the app channels feature which was not approved upstream.

**Comment by jmattheis** [comment]
@quthla In https://github.com/quthla/android/commit/85f1b0282b27c268f870ff7c590d8c616ef9f049 you've commented out the disconnect on network loss, did this create any problems?

**Comment by quthla** [comment]
As I said I was using that on 2.0.12 and before and am not using it anymore now after you fixed reconnect yourself.

The issue was that back then it would never reconnect when it took that path so I commented it out as a quick fix. Unfortunately I'm not able to tell you the exact reason as it was more than a year ago when I did that.

**Comment by MnM001** [comment]
Updated to version 2.1.0 - the issue remains the same.

**Comment by jmattheis** [comment]
Could you show more log from the android app?

**Comment by MnM001** [comment]
2021-02-17T03:56:54.999Z INFO: Entering LogsActivity
2021-02-17T03:56:52.924Z INFO: Loading more messages for -1
2021-02-17T03:56:52.921Z INFO: Entering MessagesActivity
2021-02-17T03:56:52.905Z INFO: Server version: 2.0.21@2021-01-06-15:38:32
2021-02-17T03:56:52.901Z INFO: WebSocket(9): opened
2021-02-17T03:56:52.756Z INFO: Network reconnected
2021-02-17T03:56:52.754Z INFO: WebSocket(9): starting...
2021-02-17T03:56:52.753Z INFO: Starting WebSocketService
2021-02-17T03:56:52.753Z INFO: WebSocket(8): closing existing connection.
2021-02-17T03:56:52.751Z INFO: Authenticated as MnM
2021-02-17T03:56:52.622Z INFO: Entering InitializationActivity
2021-02-17T03:55:15.470Z INFO: WebSocket(8): opened
2021-02-17T03:55:15.356Z INFO: WebSocket(8): starting...
2021-02-17T03:55:15.355Z INFO: WebSocket(7): closing existing connection.
2021-02-17T03:54:15.351Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2021-02-17T03:54:15.277Z ERROR: WebSocket(7): failure  Message: 
java.net.SocketException: Software caused connection abort
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
at java.net.SocketInputStream.read(SocketInputStream.java:176)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
at okio.Okio$2.read(Okio.java:140)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.request(RealBufferedSource.java:68)
at okio.RealBufferedSource.require(RealBufferedSource.java:61)
at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
2021-02-17T03:54:15.273Z ERROR: WebSocket(6): failure  Message: 
java.net.SocketException: Software caused connection abort
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
at java.net.SocketInputStream.read(SocketInputStream.java:176)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
at okio.Okio$2.read(Okio.java:140)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.request(RealBufferedSource.java:68)
at okio.RealBufferedSource.require(RealBufferedSource.java:61)
at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
2021-02-17T03:49:17.375Z INFO: WebSocket(7): opened
2021-02-17T03:49:17.322Z INFO: WebSocket(7): starting...
2021-02-17T03:48:21.869Z INFO: Entering LogsActivity
2021-02-17T03:48:19.268Z INFO: Loading more messages for -1
2021-02-17T03:48:19.263Z INFO: Entering MessagesActivity
2021-02-17T03:48:19.260Z INFO: WebSocket(6): opened
2021-02-17T03:48:19.247Z INFO: Server version: 2.0.21@2021-01-06-15:38:32
2021-02-17T03:48:19.195Z INFO: Network reconnected
2021-02-17T03:48:19.191Z INFO: WebSocket(6): starting...
2021-02-17T03:48:19.190Z INFO: Starting WebSocketService
2021-02-17T03:48:19.190Z INFO: WebSocket(5): closing existing connection.
2021-02-17T03:48:19.188Z INFO: Authenticated as MnM
2021-02-17T03:48:19.134Z INFO: Entering InitializationActivity
2021-02-17T03:48:17.310Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2021-02-17T03:48:17.303Z ERROR: WebSocket(5): failure  Message: 
java.net.SocketException: Software caused connection abort
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
at java.net.SocketInputStream.read(SocketInputStream.java:176)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
at okio.Okio$2.read(Okio.java:140)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.request(RealBufferedSource.java:68)
at okio.RealBufferedSource.require(RealBufferedSource.java:61)
at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
2021-02-17T03:37:00.380Z INFO: WebSocket(5): opened
2021-02-17T03:37:00.335Z INFO: WebSocket(5): starting...
2021-02-17T03:37:00.334Z INFO: WebSocket(4): closing existing connection.
2021-02-17T03:24:56.228Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2021-02-17T03:24:56.219Z ERROR: WebSocket(4): failure  Message: 
java.net.SocketException: Software caused connection abort
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
at java.net.SocketInputStream.read(SocketInputStream.java:176)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:936)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:900)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:815)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:788)
at okio.Okio$2.read(Okio.java:140)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.request(RealBufferedSource.java:68)
at okio.RealBufferedSource.require(RealBufferedSource.java:61)
at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
2021-02-17T03:13:19.536Z INFO: WebSocket(4): opened
2021-02-17T03:13:19.465Z INFO: WebSocket(4): starting...
2021-02-17T03:13:19.463Z INFO: WebSocket(3): closing existing connection.

**Comment by jmattheis** [comment]
The log contains "Network reconnected", which basically means you phone lost its internet connection.

**Comment by MnM001** [comment]
Your comments led me to investigate further.

It ended up being an issue with my phone and the firmware.
After updating the phone to latest firmware all runs good now. No more disconnections/reconnections.

Closing this now as all works as it should.

Thanks.

**Comment by quthla** [comment]
@jmattheis it seems you unfortunately were not able to fix the reconnect issues after all

2021-03-09T23:19:45.083Z INFO: Network reconnected
2021-03-09T19:52:20.617Z INFO: WebSocket(28): Network not connected

The network obviously was not disconnected for that huge amount of time but it seems the callback is received too late. That was also the reason for the fix you saw in my commit history. It does occur about once or twice a day.

**Comment by jmattheis** [comment]
That sucks. Then the only fix would be to ignore the network status and reconnect regardless.

**Comment by quthla** [comment]
That's exactly what my fix did back then

I also have messages like this in the log

2021-03-11T10:24:18.213Z INFO: Network reconnected
2021-03-11T10:24:18.213Z INFO: Network reconnected
2021-03-11T10:24:18.211Z INFO: Network reconnected
2021-03-11T10:24:18.210Z INFO: Network reconnected
2021-03-11T10:24:18.188Z INFO: Network reconnected
2021-03-11T10:24:18.188Z INFO: Network reconnected
2021-03-11T10:24:18.187Z INFO: Network reconnected
2021-03-11T10:24:18.186Z INFO: Network reconnected
... 
2021-03-11T10:19:15.916Z INFO: Network reconnected
2021-03-11T10:19:15.916Z INFO: Network reconnected
2021-03-11T10:19:15.915Z INFO: Network reconnected
2021-03-11T10:19:15.912Z INFO: Network reconnected

**Comment by quthla** [comment]
I'd suggest you just let it reconnect forever with an exponential backoff algorithm from 5 to 60 seconds or so

**Comment by jmattheis** [comment]
Would you like to create a PR for this? This would include deleting the reconnect listener and the disconnect callback.

Gotify already does an exponential back off with a max of 20minutes.

**Comment by quthla** [comment]
I would but unfortunately at the moment I don't have Android Studio set up. That's also why I'm using CI to build my fork and doing any more complicated work without proper IDE is quite a pain.

**Comment by jmattheis** [comment]
Alright, I'll see if I find some time for this.

**Comment by quthla** [comment]
2021-03-14T10:11:11.445Z INFO: Entering InitializationActivity
2021-03-14T07:39:04.026Z INFO: WebSocket(2): Network not connected

Still happening but I've just switched to that tag of mine with the fix included until you maybe find time to rip out the connectivity handler stuff

**Comment by alexitx** [comment]
I'm experiencing this exact issue on Android 11. Except I don't always get 'Network reconnected' or 'Network not connected', only saw it once during my limited testing.

Every ~10 minutes on the server I get:
```
WebSocket: ReadError read tcp X:X->X: wsarecv: An existing connection was forcibly closed by the remote host
```
and on the client:
```
WebSocket: opened
WebSocket: starting...
WebSocket: closing existing connection.
WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
ERROR: WebSocket(): falure Message:
java.net.SocketException: Software caused connection abort
```

Tried both 2.4GHz and 5GHz wifi. Verified that no firewall is blocking or limiting the connection. The Gotify app is set to never sleep, allowed to use background data, and the server is on the local network. I can ping the phone from other devices and from the router even after it has been idle for hours.

Unlocking the phone doesn't always cause the app to reconnect, but instead sits on the "Connection failed, trying again in 1 minutes" notification. Opening gotify and clicking reload from the menu restores the connection.

gotify/server v2.1.4 running on Windows 10 or Ubuntu Server 22.04
gotify/android v2.3.3 running on Galaxy A70 with latest patches for Android 11

**Comment by jmattheis** [comment]
@alexitx open a new issue, include full logs for gotify/server & android for more than 20 minutes. Include reverse proxy configs and your gotify/server settings.
