### ISSUE TITLE
Null application image causes `gotify` application to crash

### ISSUE THREAD

**Issue by dcousens** [gotify/android#170]
If `/application` responds with a response akin to
```
[
  {
    "description": "...",
    "id": 5,
    "image": null,
    "internal": false,
    "name": "...",
    "token": "..."
  }
]
```

You will see `gotify` crash.  `v2.1.2`.
Same result if the `image` field is omitted.

This isn't a normal response from the `gotify` server. 

That said, the application should probably _not_ crash.

Relevant ERROR
```
2021-04-25T05:01:08.332Z ERROR: uncaught exception
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019)
    at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014)
    at com.github.gotify.messages.provider.MessageImageCombiner.appIdToImage(MessageImageCombiner.java:32)
    at com.github.gotify.picasso.PicassoHandler.lambda$updateAppIds$0$PicassoHandler(PicassoHandler.java:83)
    at com.github.gotify.picasso.-$$Lambda$PicassoHandler$lvphCfdLYDTIyv6p4Kc3INEHQcE.onSuccess(Unknown Source:4)
    at com.github.gotify.api.Callback.lambda$merge$8(Callback.java:44)
    at com.github.gotify.api.-$$Lambda$Callback$4pGTPSjU5QTSLq-xj2oBHzruxcU.onSuccess(Unknown Source:4)
    at com.github.gotify.api.Callback$RetrofitCallback.onResponse(Callback.java:72)
    at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7660)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by jmattheis** [comment]
What do you mean with
> This isn't a normal response from the gotify server.

Do you use a modified version of gotify/server?

**Comment by dcousens** [comment]
> Do you use a modified version of gotify/server?

Yes,  and I understand if you might consider that out-of-scope,  but an NPE is still less than ideal.

**Comment by jmattheis** [comment]
Would you mind sharing what kind of alternative you use? gotify/server defines an [API contract in which "image" is marked as required field](https://github.com/gotify/server/blob/9abe803cf89e9a5d9fc37026544fa3b5e905eedd/docs/spec.json#L1903). If the alternative server wants to support the gotify/android client, then it must adhere to this api contract.

**Comment by dcousens** [comment]
@jmattheis it's a local application,  nothing released.
I'm happy to close this issue if you don't think the NPE opportunity is a problem.
