### ISSUE TITLE
Unable to start activity ComponentInfo{com.github.gotify/com.github.gotify.messages.MessagesActivity}

### ISSUE THREAD

**Issue by rgegriff** [gotify/android#174]
Hi! I am trying to install gotify in... a somewhat strange environment. Specifically a rooted nook glowlight ereader. I am able to start gotify, and connect it to my server, but immediately after I do that, the app seems to crash out and I see this error in logcat (listed below)

I am not _super_ familiar with android internals, so I am a little stumped as to if I should be looking at this app or something about the environment as the next steps. If anyone has any advice, I would be appreciative! 

```
I/gotify  ( 6352): WebSocket(1): opened
I/gotify  ( 6352): Entering MessagesActivity
E/gotify  ( 6352): uncaught exception
E/gotify  ( 6352): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.gotify/com.github.gotify.messages.MessagesActivity}: android.content.res.Resources$NotFoundException: File res/drawable/ic_delete.xml from drawable resource ID #0x7f080072
E/gotify  ( 6352): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
E/gotify  ( 6352): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/gotify  ( 6352): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/gotify  ( 6352): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/gotify  ( 6352): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/gotify  ( 6352): 	at android.os.Looper.loop(Looper.java:136)
E/gotify  ( 6352): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/gotify  ( 6352): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/gotify  ( 6352): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/gotify  ( 6352): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/gotify  ( 6352): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/gotify  ( 6352): 	at dalvik.system.NativeStart.main(Native Method)
E/gotify  ( 6352): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_delete.xml from drawable resource ID #0x7f080072
E/gotify  ( 6352): 	at android.content.res.Resources.loadDrawable(Resources.java:2096)
E/gotify  ( 6352): 	at android.content.res.Resources.getDrawable(Resources.java:700)
E/gotify  ( 6352): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:457)
E/gotify  ( 6352): 	at com.github.gotify.messages.MessagesActivity$SwipeToDeleteCallback.<init>(MessagesActivity.java:444)
E/gotify  ( 6352): 	at com.github.gotify.messages.MessagesActivity.onCreate(MessagesActivity.java:165)
E/gotify  ( 6352): 	at android.app.Activity.performCreate(Activity.java:5270)
E/gotify  ( 6352): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/gotify  ( 6352): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
E/gotify  ( 6352): 	... 11 more
E/gotify  ( 6352): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
E/gotify  ( 6352): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/gotify  ( 6352): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/gotify  ( 6352): 	at android.content.res.Resources.loadDrawable(Resources.java:2092)
E/gotify  ( 6352): 	... 18 more
E/gotify  ( 6352): 
W/ActivityManager( 2447): Activity destroy timeout for ActivityRecord{414a8d60 u0 com.github.gotify/.login.LoginActivity t21 f}
```

**Comment by jmattheis** [comment]
Which android version does it run?

**Comment by rgegriff** [comment]
Ack! Sorry, I thought I mentioned that. It's 4.4

**Comment by jmattheis** [comment]
Gotify now only supports >= Android 6.0
