### ISSUE TITLE
Disable send button if the user has no apps

### ISSUE THREAD

**Issue by ErSauravAdhikari** [gotify/android#179]
In the push message tab, on a new gotify server, that has no app set up. When you press the push message, with other fields filled,The app Freezes.

![Screenshot_2021-06-25-10-34-14-11.png](https://user-images.githubusercontent.com/69170305/123371160-e9448e80-d5a0-11eb-8792-d51915e0a831.png)

Method to replicate:
1. Create a new gotify server (Or use one that has no apps setup).
2. Connect via a client android app. 
3. Go to Push Message tab
![Screenshot_2021-06-25-10-36-18-86.png](https://user-images.githubusercontent.com/69170305/123371315-3d4f7300-d5a1-11eb-8c8d-8bd311baa02a.png)
4. Then write down the title and content fields and press this button. (There is not app there)
![Screenshot_2021-06-25-10-36-30-70.png](https://user-images.githubusercontent.com/69170305/123371355-58ba7e00-d5a1-11eb-82f9-cfd765aaf668.png)
5. Freeze your android app. (Happens automatically 😊😊)

**Comment by ErSauravAdhikari** [comment]
Here is whatever I could copy from the logs.

```
Saurav Adhikari, [25.06.21 14:35]
2021-06-25T08:49:29.917Z INFO: Entering LogsActivity
2021-06-25T08:49:27.397Z INFO: Loading more messages for -1
2021-06-25T08:49:27.335Z INFO: Entering MessagesActivity
2021-06-25T08:49:27.163Z INFO: Server version: 2.0.22@2021-04-16-18:16:19
2021-06-25T08:49:26.178Z INFO: WebSocket(1): opened
2021-06-25T08:49:25.541Z INFO: WebSocket(1): starting...
2021-06-25T08:49:25.523Z INFO: Starting WebSocketService
2021-06-25T08:49:25.516Z INFO: Create WebSocketService
2021-06-25T08:49:25.506Z INFO: Authenticated as admin
2021-06-25T08:49:23.272Z INFO: Entering InitializationActivity
2021-06-25T04:51:21.174Z INFO: Entering ShareActivity
2021-06-25T04:51:09.497Z INFO: Entering ShareActivity
2021-06-25T04:51:05.782Z INFO: Loading more messages for -1
2021-06-25T04:51:05.732Z INFO: Entering MessagesActivity
2021-06-25T04:51:05.620Z INFO: WebSocket(1): opened
2021-06-25T04:51:05.571Z INFO: Server version: 2.0.22@2021-04-16-18:16:19
2021-06-25T04:51:05.032Z INFO: WebSocket(1): starting...
2021-06-25T04:51:05.016Z INFO: Starting WebSocketService
2021-06-25T04:51:05.009Z INFO: Create WebSocketService
2021-06-25T04:51:05.001Z INFO: Authenticated as admin
2021-06-25T04:51:03.790Z INFO: Entering InitializationActivity
2021-06-25T04:49:06.521Z ERROR: uncaught exception
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
 at java.util.ArrayList.get(ArrayList.java:439)
 at com.github.gotify.sharing.ShareActivity.pushMessage(ShareActivity.java:109)
 at com.github.gotify.sharing.ShareActivity_ViewBinding$1.doClick(ShareActivity_ViewBinding.java:40)
 at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:26)
 at android.view.View.performClick(View.java:6392)
 at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
 at android.view.View$PerformClick.run(View.java:25133)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:198)
 at android.app.ActivityThread.main(ActivityThread.java:7055)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

2021-06-25T04:48:46.595Z INFO: Entering ShareActivity
2021-06-25T04:48:44.093Z INFO: Loading more messages for -1
2021-06-25T04:48:44.043Z INFO: Entering MessagesActivity
2021-06-25T04:48:43.893Z INFO: Server version: 2.0.22@2021-04-16-18:16:19
2021-06-25T04:48:43.877Z INFO: WebSocket(1): opened
2021-06-25T04:48:43.295Z INFO: WebSocket(1): starting...
2021-06-25T04:48:43.278Z INFO: Starting WebSocketService
2021-06-25T04:48:43.270Z INFO: Create WebSocketService
2021-06-25T04:48:43.261Z INFO: Authenticated as admin
2021-06-25T04:48:42.576Z INFO: Entering InitializationActivity
2021-06-25T04:45:54.417Z ERROR: uncaught exception
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
 at java.util.ArrayList.get(ArrayList.java:439)
 at com.github.gotify.sharing.ShareActivity.pushMessage(ShareActivity.java:109)
 at com.github.gotify.sharing.ShareActivity_ViewBinding$1.doClick(ShareActivity_ViewBinding.java:40)
 at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:26)
 at android.view.View.performClick(View.java:6392)
 at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
 at android.view.View$PerformClick.run(View.java:25133)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:198)
 at android.app.ActivityThread.main(ActivityThread.java:7055)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

Saurav Adhikari, [25.06.21 14:35]
2021-06-25T04:45:46.765Z INFO: Entering ShareActivity
2021-06-25T04:45:44.335Z INFO: Loading more messages for -1
2021-06-25T04:45:44.288Z INFO: Entering MessagesActivity
2021-06-25T04:45:44.173Z INFO: WebSocket(1): opened
2021-06-25T04:45:44.134Z INFO: Server version: 2.0.22@2021-04-16-18:16:19
2021-06-25T04:45:43.594Z INFO: WebSocket(1): starting...
2021-06-25T04:45:43.576Z INFO: Starting WebSocketService
2021-06-25T04:45:43.568Z INFO: Create WebSocketService
2021-06-25T04:45:43.558Z INFO: Authenticated as admin
2021-06-25T04:45:42.928Z INFO: Entering InitializationActivity
2021-06-25T04:45:27.289Z ERROR: uncaught exception
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
 at java.util.ArrayList.get(ArrayList.java:439)
 at com.github.gotify.sharing.ShareActivity.pushMessage(ShareActivity.java:109)
 at com.github.gotify.sharing.ShareActivity_ViewBinding$1.doClick(ShareActivity_ViewBinding.java:40)
 at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:26)
 at android.view.View.performClick(View.java:6392)
 at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
 at android.view.View$PerformClick.run(View.java:25133)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:198)
 at android.app.ActivityThread.main(ActivityThread.java:7055)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

2021-06-25T04:45:17.182Z INFO: Entering ShareActivity
2021-06-25T04:45:14.136Z INFO: Loading more messages for -1
2021-06-25T04:45:14.085Z INFO: Entering MessagesActivity
2021-06-25T04:45:14.034Z INFO: WebSocket(1): opened
2021-06-25T04:45:13.956Z INFO: Server version: 2.0.22@2021-04-16-18:16:19
2021-06-25T04:45:13.427Z INFO: WebSocket(1): starting...
2021-06-25T04:45:13.403Z INFO: Starting WebSocketService
2021-06-25T04:45:13.389Z INFO: Create WebSocketService
2021-06-25T04:45:13.370Z INFO: Authenticated as admin
2021-06-25T04:45:12.736Z INFO: Entering InitializationActivity
2021-06-25T04:44:40.861Z INFO: Entering LoginActivity
2021-06-25T04:44:39.420Z ERROR: Error while api call
Code(0) Response: 
 at com.github.gotify.api.Callback$RetrofitCallback.onFailure(Callback.java:80)
 at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:80)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:198)
 at android.app.ActivityThread.main(ActivityThread.java:7055)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
 at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
 at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
 at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)

Saurav Adhikari, [25.06.21 14:35]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at com.github.gotify.client.auth.ApiKeyAuth.intercept(ApiKeyAuth.java:66)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
 at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
 at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)
 at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
 at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
 at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
 at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
 at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
 at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
 at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
 at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
 at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
 at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
 ... 26 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

**Comment by jmattheis** [comment]
Jip, you need apps to send messages. The send button should probably be disabled, if the user has no apps.
