### ISSUE TITLE
when using http2 its not possible to make api calls

### ISSUE THREAD

**Issue by jmattheis** [gotify/android#24]
See gotify/server#70

**Comment by xp-1000** [comment]
Thanks @jmattheis.
I will be happy to help if you need.

**Comment by flocke** [comment]
Just ran into this issue when trying to connect to my gotify server using my nginx proxy.
I'm happy to help with testing and debugging if you need anything.

**Comment by jmattheis** [comment]
@xp-1000 @flocke Could you try out the latest release? The apk can be downloaded [here](https://github.com/gotify/android/releases/tag/v2.0.3).

**Comment by xp-1000** [comment]
hello @jmattheis I confirm it works fine ! thanks for quick fix.
Seems it have only one problem left, when I reboot my phone gotify does not start automatically even if I configure battery optimization to don't optimize gotify.
But this is another problem and probably from my android, when gotify is manually started all is working fine.
thanks, from my opinion you can close this issue.

**Comment by jmattheis** [comment]
@xp-1000 There is already an issue for starting Gotify on boot https://github.com/gotify/android/issues/25

**Comment by flocke** [comment]
I can confirm as well that it works now.

It just reconnects a lot for me (every couple of minutes). Maybe I have to take a look at my nginx config again...

**Comment by gelse** [comment]
Sorry to be a downer, but it seems as if this bug is here again.

> 2021-04-18T07:35:42.303Z INFO: Entering LogsActivity
2021-04-18T07:35:37.768Z INFO: Removing message with id 63
2021-04-18T07:35:28.287Z INFO: Loading more messages for -1
2021-04-18T07:35:28.262Z INFO: Entering MessagesActivity
2021-04-18T07:35:28.251Z INFO: WebSocket(1): closing existing connection.
2021-04-18T07:35:28.249Z ERROR: WebSocket(1): failure StatusCode: 400 Message: Bad Request
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

2021-04-18T07:35:28.181Z INFO: Server version: 2.0.22@2021-04-16-18:16:19
2021-04-18T07:35:28.087Z INFO: Network reconnected
2021-04-18T07:35:28.074Z INFO: WebSocket(1): starting...
2021-04-18T07:35:28.035Z INFO: Starting WebSocketService
2021-04-18T07:35:28.028Z INFO: Create WebSocketService
2021-04-18T07:35:28.020Z INFO: Authenticated as admin
2021-04-18T07:35:27.875Z INFO: Entering InitializationActivity
2021-04-18T07:35:03.957Z INFO: Entering LoginActivity
2021-04-18T07:35:03.846Z INFO: Entering InitializationActivity

Server version is in the logs, docker installation behind an Apache reverse proxy and client version 2.1.1

**Comment by jmattheis** [comment]
@gelse Open a new issue for this, include gotify/server log and your reverse proxy configuration.
