### ISSUE TITLE
"Could not connect / Bad request" notification

### ISSUE THREAD

**Issue by dokho33** [gotify/android#254]
Hi.

First sorry for my english :)

I have installed gotify with docker and use nginx proxy manager to redirect https://gotify.mydomain.fr to the gotify container port

I have a "Could not connect / Bad request" notification on android app.

I'm sure it's a proxy configuration problem but i can't find anything to configure gotify with nginx proxy manager.

I have try to add this in the advanced configuration of the proxy host (in nginx proxy manager interface):
```
proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto http;
    proxy_redirect     http:// $scheme://;

    # The proxy must preserve the host because gotify verifies the host with the origin
    # for WebSocket connections
    proxy_set_header   Host $http_host;

    # These sets the timeout so that the websocket can stay alive
    proxy_connect_timeout   1m;
    proxy_send_timeout      1m;
    proxy_read_timeout      1m;
```

But it don't work.

This is the app error log:
```
2022-10-31T16:02:29.173Z INFO: Entering LogsActivity
2022-10-31T16:00:58.544Z INFO: Entering LogsActivity
2022-10-31T16:00:55.673Z INFO: Loading more messages for -1
2022-10-31T16:00:55.665Z INFO: Entering MessagesActivity
2022-10-31T16:00:55.603Z INFO: WebSocket(1): closing existing connection.
2022-10-31T16:00:55.601Z INFO: Server version: 2.1.7@2022-09-11-07:29:06
2022-10-31T16:00:55.596Z ERROR: WebSocket(1): failure StatusCode: 400 Message: Bad Request
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

2022-10-31T16:00:55.457Z INFO: WebSocket(1): starting...
2022-10-31T16:00:55.450Z INFO: Starting WebSocketService
2022-10-31T16:00:55.428Z INFO: Create WebSocketService
2022-10-31T16:00:55.418Z INFO: Authenticated as ****
2022-10-31T16:00:55.275Z INFO: Entering InitializationActivity
```

Someone can help me, please ?

Regards,

**Comment by jmattheis** [comment]
Please post the gotify/server log output.

**Comment by dokho33** [comment]
This is the server log

```
Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

[GIN] 2022/10/31 - 18:24:36 | 200 |     491.791µs |     192.168.1.1 | GET      "/current/user"

[GIN] 2022/10/31 - 18:24:52 | 200 |      35.208µs |       127.0.0.1 | GET      "/health"

[GIN] 2022/10/31 - 18:25:07 | 200 |      50.079µs |    77.205.53.81 | GET      "/version"

[GIN] 2022/10/31 - 18:25:19 | 200 |      45.558µs |    77.205.53.81 | GET      "/version"

[GIN] 2022/10/31 - 18:25:23 | 200 |      35.005µs |       127.0.0.1 | GET      "/health"

[GIN] 2022/10/31 - 18:25:30 | 200 |  114.674886ms |    77.205.53.81 | GET      "/current/user"

[GIN] 2022/10/31 - 18:25:32 | 200 |  317.763174ms |    77.205.53.81 | POST     "/client"

[GIN] 2022/10/31 - 18:25:32 | 200 |     517.267µs |    77.205.53.81 | GET      "/current/user"

[GIN] 2022/10/31 - 18:25:32 | 200 |      74.511µs |    77.205.53.81 | GET      "/version"

[GIN] 2022/10/31 - 18:25:32 | 200 |     606.269µs |    77.205.53.81 | GET      "/message?limit=1&since=0"

[GIN] 2022/10/31 - 18:25:32 | 400 |     308.457µs |    77.205.53.81 | GET      "/stream?token=[masked]"

Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

[GIN] 2022/10/31 - 18:25:32 | 200 |      527.41µs |    77.205.53.81 | GET      "/application"

[GIN] 2022/10/31 - 18:25:33 | 200 |     883.743µs |    77.205.53.81 | GET      "/message?limit=100&since=0"

[GIN] 2022/10/31 - 18:25:33 | 200 |    1.226376ms |    77.205.53.81 | GET      "/application"

[GIN] 2022/10/31 - 18:25:33 | 200 |     393.007µs |    77.205.53.81 | GET      "/static/defaultapp.png"

[GIN] 2022/10/31 - 18:25:33 | 200 |     626.138µs |    77.205.53.81 | GET      "/static/defaultapp.png"

[GIN] 2022/10/31 - 18:25:36 | 400 |     456.867µs |     192.168.1.1 | GET      "/stream?token=[masked]"

Error #01: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header

[GIN] 2022/10/31 - 18:25:36 | 200 |     496.469µs |     192.168.1.1 | GET      "/current/user"

[GIN] 2022/10/31 - 18:25:53 | 200 |      32.031µs |       127.0.0.1 | GET      "/health"
```

**Comment by jmattheis** [comment]
The `Connection: upgrade` header isn't passed in the response. The config you posted with `proxy_set_header   Connection "upgrade";` most likely isn't correctly applied.

**Comment by dokho33** [comment]
I'm stupid: there is a "websockets support" option in nginx proxy manager ...

It's work.

Thank you for help @jmattheis
