### ISSUE TITLE
Websocket issue with app

### ISSUE THREAD

**Issue by xlemassacre** [gotify/android#284]
Hey, I've installed the gotify server on a kubernetes cluster behind an ingress controller.
_gotify/server v2.2.4
gotify/android v2.5.1_

The setup seems to be lookign good, browser is working fine, but i have a lot of websocket issues with the app:

```
2023-03-14T12:58:50.432Z INFO: Entering LogsActivity
2023-03-14T12:58:24.893Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2023-03-14T12:58:24.824Z ERROR: WebSocket(31): failure  Message: 
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:68)
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

2023-03-14T12:45:15.043Z INFO: WebSocket(31): opened
2023-03-14T12:45:14.878Z INFO: WebSocket(31): starting...
2023-03-14T12:45:14.877Z INFO: WebSocket(30): closing existing connection.
2023-03-14T12:40:42.571Z INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2023-03-14T12:40:42.556Z ERROR: WebSocket(30): failure  Message: 
java.net.SocketException: Software caused connection abort
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
	at java.net.SocketInputStream.read(SocketInputStream.java:173)
	at java.net.SocketInputStream.read(SocketInputStream.java:143)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:68)
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

It looks to me like a problem with the app, the browser has a working websocket for many hours at the same time:
![image](https://user-images.githubusercontent.com/94062451/225016940-5d49da44-247a-4e4c-abd1-7e646ee15e17.png)

I have also tried different ingress settings (timeouts, ...) but still have that issue. 
Is this problem a code issue or a network problem?

**Comment by jmattheis** [comment]
Most likely a network problem, as it does work with your browser setup. Do you use a mobile network or wlan / wifi. If it's mobile, then it's pretty common that the connection breaks. What does gotify/server log when gotify/android loses the connection?

**Comment by xlemassacre** [comment]
This is happening with wifi, my phone(app) and the laptop(browser) are in the same wifi at the same place.

There are a lot of errors in the log for the phone, but none for the laptop.
```
2023-03-14T15:41:41.297716740+01:00 [GIN] 2023/03/14 - 15:41:41 | 200 |    1.390856ms |   192.168.1.111 | GET      "/stream?token=[masked]"
2023-03-14T15:41:41.340378225+01:00 [GIN] 2023/03/14 - 15:41:41 | 200 |    1.901194ms |   192.168.1.111 | GET      "/message?limit=10"
2023-03-14T15:41:41.675426638+01:00 WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
2023-03-14T15:43:00.678558548+01:00 [GIN] 2023/03/14 - 15:43:00 | 200 |    1.240353ms |   192.168.1.111 | GET      "/stream?token=[masked]"
2023-03-14T15:43:00.738034499+01:00 [GIN] 2023/03/14 - 15:43:00 | 200 |    1.631205ms |   192.168.1.111 | GET      "/message?limit=10"
2023-03-14T15:44:43.407887218+01:00 WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
2023-03-14T15:51:00.183203999+01:00 [GIN] 2023/03/14 - 15:51:00 | 200 |    1.542603ms |   192.168.1.111 | GET      "/stream?token=[masked]"
2023-03-14T15:51:00.243312827+01:00 [GIN] 2023/03/14 - 15:51:00 | 200 |    1.075611ms |   192.168.1.111 | GET      "/message?limit=10"
2023-03-14T15:51:37.014290388+01:00 WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
2023-03-14T16:18:06.287748798+01:00 [GIN] 2023/03/14 - 16:18:06 | 200 |     997.254µs |   192.168.1.111 | GET      "/stream?token=[masked]"
2023-03-14T16:18:06.365534318+01:00 [GIN] 2023/03/14 - 16:18:06 | 200 |    1.666885ms |   192.168.1.111 | GET      "/message?limit=10"
2023-03-14T16:20:16.510943149+01:00 WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
2023-03-14T16:22:59.320424603+01:00 [GIN] 2023/03/14 - 16:22:59 | 200 |    1.246257ms |   192.168.1.111 | GET      "/stream?token=[masked]"
2023-03-14T16:22:59.407005272+01:00 [GIN] 2023/03/14 - 16:22:59 | 200 |    1.213049ms |   192.168.1.111 | GET      "/message?limit=10"
2023-03-14T16:24:29.490894809+01:00 WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by jmattheis** [comment]
You could try to deploy gotify without kubernetes and connect directly to it and check if the error persists. gotify/server says connection was aborted without a properly closing it and same is true for gotify/andoird.

**Comment by jmattheis** [comment]
But yeah, probably nothing we can do, the connection works for the browser but not for the android app. It's a pretty low level exception on the android app.

**Comment by xlemassacre** [comment]
Sorry I had no time yet to test the k8s-less installation. I'll do that when I have more time and open another ticket if necessary.
