### ISSUE TITLE
Error 400 Bad Request

### ISSUE THREAD

**Issue by felixq** [gotify/android#299]
Through the web interface the messages are seen correctly but through the apk they are not seen.

2023-06-06T15:11:09.029Z INFO: Entering LogsActivity
2023-06-06T15:08:41.186Z INFO: Entering LogsActivity
2023-06-06T15:07:09.921Z INFO: Entering ShareActivity
2023-06-06T15:06:36.691Z INFO: Entering LogsActivity
2023-06-06T15:06:02.796Z INFO: Loading more messages for -1
2023-06-06T15:06:02.752Z INFO: Entering MessagesActivity
2023-06-06T15:06:02.629Z INFO: WebSocket(2): closing existing connection.
2023-06-06T15:06:02.622Z ERROR: WebSocket(2): failure StatusCode: 400 Message: Bad Request
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

2023-06-06T15:06:02.602Z INFO: Server version: 2.2.4@2023-01-10-18:33:52
2023-06-06T15:06:02.021Z INFO: WebSocket(2): starting...
2023-06-06T15:06:02.014Z INFO: Starting WebSocketService
2023-06-06T15:06:01.996Z INFO: Authenticated as usuariotest
2023-06-06T15:06:01.626Z INFO: Entering InitializationActivity
2023-06-06T15:05:45.673Z INFO: Loading more messages for -1
2023-06-06T15:05:45.478Z INFO: Entering MessagesActivity
2023-06-06T15:05:45.152Z INFO: WebSocket(1): closing existing connection.
2023-06-06T15:05:45.121Z INFO: Server version: 2.2.4@2023-01-10-18:33:52
2023-06-06T15:05:45.115Z ERROR: WebSocket(1): failure StatusCode: 400 Message: Bad Request
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

2023-06-06T15:05:44.739Z INFO: WebSocket(1): starting...
2023-06-06T15:05:44.679Z INFO: Starting WebSocketService
2023-06-06T15:05:44.523Z INFO: Create WebSocketService
2023-06-06T15:05:44.483Z INFO: Authenticated as usuariotest
2023-06-06T15:05:44.103Z INFO: Entering InitializationActivity
2023-06-06T14:59:50.077Z INFO: Entering LoginActivity
2023-06-06T14:59:49.791Z INFO: Entering InitializationActivity

**Comment by jmattheis** [comment]
Have you looked through existing issues? https://github.com/gotify/android/issues?q=is%3Aissue+400+bad+request+is%3Aclosed

**Comment by felixq** [comment]
I looked in the open ones but it did not occur to me to look for the closed ones.
thank you
