### ISSUE TITLE
Message "could not connect - unauthorized"

### ISSUE THREAD

**Issue by Sylvan86** [gotify/android#305]
After reinstalling my phone, I no longer receive messages as push notifications from Gotify.

On the server side, I haven't changed anything from before when everything was working.
The Gotify app logs into the server and shows correctly all apps and messages.
However, the message "_Could not connect - Unauthorized_" is brought up as a persistent notification.
The app has all the necessary rights and battery options have been turned off on a manufacturer-specific basis.

However, when I send a message, it is displayed instantaneously in the PC browser in the web interface.
In the android app, however, not (and also the notification for this remains off).
Only when I manually refresh the message list by "pulling down", the message is also displayed in the app.
The message "_could not connect_" still exists.

In the logs, the following noticeable entries can be found:
```
2023-07-18T04:21:37.334Z INFO: Server version: 2.2.5@2023-06-26-19:20:05
2023-07-18T04:21:37.313Z INFO: WebSocket: Network available, reconnect if needed.
2023-07-18T04:21:37.308Z INFO: WebSocket(1): starting...
2023-07-18T04:21:37.301Z INFO: Starting WebSocketService
2023-07-18T04:21:37.283Z INFO: Create WebSocketService
2023-07-18T04:21:37.268Z INFO: Authenticated as xxx
2023-07-18T04:21:37.139Z INFO: Entering InitializationActivity
2023-07-18T04:21:24.049Z INFO: Loading more messages for 1
2023-07-18T04:20:55.059Z INFO: Entering ShareActivity
2023-07-18T04:15:09.980Z INFO: Loading more messages for -1
2023-07-18T04:15:09.892Z INFO: Entering MessagesActivity
2023-07-18T04:15:09.815Z ERROR: WebSocket(1): failure StatusCode: 401 Message: Unauthorized
java.net.ProtocolException: Expected HTTP 101 response but was '401 Unauthorized'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

The Gotify server is behind an nginx proxy.
The settings for the gotify server look like this:
```nginx
server {
	server_name gotify.*;

	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	# all ssl related config moved to ssl.conf
	include /config/nginx/ssl.conf;

	# activate HSTS
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

	location / {
		proxy_pass http://192.168.0.8:887/;

		# Ensuring it can use websockets
		proxy_set_header   Upgrade $http_upgrade;
		proxy_set_header   Connection "upgrade";
		proxy_set_header   X-Real-IP $remote_addr;
		proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Proto http;
		proxy_redirect     http:// $scheme://;

		# The proxy must preserve the host because gotify verifies the host with the origin
		# for WebSocket connections
		proxy_set_header   Host $http_host;

		# These sets the timeout so that the websocket can stay alive
		proxy_connect_timeout   1m;
		proxy_send_timeout      1m;
		proxy_read_timeout      1m;
	}
}
```

**Comment by Sylvan86** [comment]
The fault was exclusively mine. The hint with the server log brought the solution:
There the login process was logged with the following URL: "_/stream?token=[masked]&token=[masked]_"

That brought me to my error: I passed the app token in the server URL in the form "_https://myServer.com/?token=xyz_".
I should have omitted the token.
