### ISSUE TITLE
could not connect bad request and no notifications but can see messages in app

### ISSUE THREAD

**Issue by BPplays** [gotify/android#310]
i get 'could not connect bad request' in my notifications, i can see new messages in the app but don't get notifications for them

some of the logs are:
```
2023-08-12T<t:1691981505:t>:44.850Z INFO: WebSocket(28): starting...
2023-08-12T<t:1691981325:t>:38.218Z INFO: WebSocket: scheduling a restart in 1200 second(s) (via alarm manager)
2023-08-12T<t:1691981325:t>:38.211Z ERROR: WebSocket(27): failure StatusCode: 502 Message: Bad Gateway
java.net.ProtocolException: Expected HTTP 101 response but was '502 Bad Gateway'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

2023-08-12T<t:1691981325:t>:38.068Z INFO: WebSocket(27): starting...
2023-08-12T<t:1691980905:t>:03.050Z INFO: WebSocket: scheduling a restart in 1200 second(s) (via alarm manager)
2023-08-12T<t:1691980905:t>:03.041Z ERROR: WebSocket(26): failure StatusCode: 502 Message: Bad Gateway
java.net.ProtocolException: Expected HTTP 101 response but was '502 Bad Gateway'
        at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012
```

**Comment by jmattheis** [comment]
Does the webui work? It's probably because of a misconfigured reverse proxy. Have you looked at the reverse proxy examples inside the gotify docs?

Post your reverse proxy configuration and the gotify/server log with +-1min when an error is logged on the android app.

**Comment by BPplays** [comment]
yes the webui works and i connect to it in the app via reverse proxy too
​
here is my reverse proxy config:
```nginx
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name gotify.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        # include /config/nginx/proxy.conf;
        # resolver 127.0.0.11 valid=30s;
        # include /config/nginx/resolver.conf;
        proxy_http_version 1.1;

        # Ensuring it can use websockets
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto http;
        proxy_redirect     http:// $scheme://;

        # The proxy must preserve the host because gotify verifies the host with the origin
        # for WebSocket connections
        proxy_set_header   Host $http_host;

        # These sets the timeout so that the websocket can stay alive
        proxy_connect_timeout   1m;
        proxy_send_timeout      1m;
        proxy_read_timeout      1m;

        set $upstream_app gotify-srv.redacted-interal-domain.org;
        set $upstream_port 8284;
        set $upstream_proto http;
        # proxy_set_header   X-Real-IP $remote_addr;
        # proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header   Host $host;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        # proxy_http_version 1.1;
        # proxy_set_header   Upgrade $http_upgrade;
        # proxy_set_header   Connection "upgrade";
    }

}
```
​
here are my logs for gotify/server:
```log
WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
2023-08-13T13:06:01Z | 200 |     225.253µs |    192.168.1.51 | GET      "/current/user"
2023-08-13T13:06:01Z | 200 |      30.559µs |    192.168.1.51 | GET      "/version"
2023-08-13T13:06:01Z | 200 |     383.979µs |    192.168.1.51 | GET      "/message?limit=1&since=0"
2023-08-13T13:06:01Z | 200 |     247.083µs |    192.168.1.51 | GET      "/application"
2023-08-13T13:06:01Z | 200 |     910.082µs |    192.168.1.51 | GET      "/stream?token=[masked]"
2023-08-13T13:06:01Z | 200 |     277.132µs |    192.168.1.51 | GET      "/application"
2023-08-13T13:06:01Z | 200 |     630.151µs |    192.168.1.51 | GET      "/message?limit=100&since=0"
2023-08-13T13:06:03Z | 200 |     372.238µs |    192.168.1.51 | GET      "/message?limit=100&since=0"
```
​
it only showed ```WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF``` right after i force quit in android btw

**Comment by BPplays** [comment]
restarting my reverse proxy seemed to have fixed it even tho it should be automatically restarted by ansible when it changes any config files. strange
