### ISSUE TITLE
Login doesn't work through Cloudflare tunnel

### ISSUE THREAD

**Issue by xenicfun** [gotify/android#332]
Hi,
I just ran into a similar issue as "Login doesn't work if the entered server URL redirects to another location #201"

My setup:
- Gotify running in docker (version 2.4.0)
- A Cloudflared connector running in a different VM, that exposes the Gotify docker (version 2024.1.4)
- I currently do **not** have any proxies (such as nginx, traefik, etc.) running

Using the internal ip, the Android app works without issue.
But once I try to through the Cloudflare tunnel, it finds the Gotify host, but gives the following error when trying to login:
"There is no user with this username of password".

I have attempted this both with admin and non-admin users.

**Comment by jmattheis** [comment]
Please add the gotify/android and gotify/server log including the entries around the time you've tried to login.

**Comment by xenicfun** [comment]
Thanks for the reply. Could you tell me where I can find the logs for Gotify (server side)?

**Comment by jmattheis** [comment]
Its logged into standard out, you should be able to get it with the docker cli: https://docs.docker.com/config/containers/logging/

**Comment by xenicfun** [comment]
Hi Jmattheis,

Strangely, after gathering the logs, it now seems to work fine. A simple closing and re-opening of the Android app seems to have done the trick. 
In case it might be usefull I have added the logs below. The Docker Compose logs did seem to indicate "Error #01: you need to provide a valid access token or user credentials to access this api"

Docker compose logs:
`compose-gotify-1  | Error #01: you need to provide a valid access token or user credentials to access this api
compose-gotify-1  | 2024-01-20T22:57:32Z | 401 |     175.349µs |   192.168.0.151 | GET      "/stream?token=[masked]"
compose-gotify-1  | Error #01: you need to provide a valid access token or user credentials to access this api
compose-gotify-1  | 2024-01-20T22:58:18Z | 401 |     153.288µs |   192.168.0.151 | GET      "/stream?token=[masked]"
compose-gotify-1  | Error #01: you need to provide a valid access token or user credentials to access this api
compose-gotify-1  | 2024-01-20T23:20:01Z | 200 |    5.778838ms |    192.168.0.10 | POST     "/message?token=[masked]"
compose-gotify-1  | 2024-01-21T05:25:01Z | 200 |    7.137603ms |    192.168.0.40 | POST     "/message"
compose-gotify-1  | 2024-01-21T11:20:02Z | 200 |    7.228175ms |    192.168.0.10 | POST     "/message?token=[masked]"
compose-gotify-1  | 2024-01-21T13:02:23Z | 200 |      63.128µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/version"
compose-gotify-1  | 2024-01-21T13:40:35Z | 401 |      65.179µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/current/user"
compose-gotify-1  | Error #01: you need to provide a valid access token or user credentials to access this api
compose-gotify-1  | 2024-01-21T13:41:22Z | 401 |      26.432µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/current/user"
compose-gotify-1  | Error #01: you need to provide a valid access token or user credentials to access this api
compose-gotify-1  | 2024-01-21T13:43:28Z | 200 |      47.701µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/version"
compose-gotify-1  | 2024-01-21T13:43:35Z | 200 |   50.028415ms | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/current/user"
compose-gotify-1  | 2024-01-21T13:43:48Z | 200 |   53.479941ms | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | POST     "/client"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     3.54034ms | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/current/user"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |      16.129µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/version"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     388.444µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/application"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     247.112µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/stream?token=[masked]"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |      572.98µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/message?limit=1&since=0"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     282.296µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/application"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     318.978µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/message?limit=100&since=0"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     236.937µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/static/defaultapp.png"
compose-gotify-1  | 2024-01-21T13:43:49Z | 200 |     131.448µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/static/defaultapp.png"
compose-gotify-1  | 2024-01-21T13:44:11Z | 200 |     400.569µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/message?limit=100&since=0"
compose-gotify-1  | WebSocket: ReadError read tcp 172.18.0.5:80->192.168.0.118:53922: i/o timeout
compose-gotify-1  | 2024-01-21T13:45:13Z | 200 |     352.566µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/message?limit=1&since=0"
compose-gotify-1  | 2024-01-21T13:45:13Z | 200 |     227.388µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/application"
compose-gotify-1  | 2024-01-21T13:45:13Z | 200 |      216.07µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/stream?token=[masked]"
compose-gotify-1  | 2024-01-21T13:45:16Z | 200 |     261.438µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/current/user"
compose-gotify-1  | 2024-01-21T13:45:19Z | 200 |     284.091µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/stream?token=[masked]"
compose-gotify-1  | 2024-01-21T13:45:19Z | 200 |      11.614µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/version"
compose-gotify-1  | 2024-01-21T13:45:19Z | 200 |     264.668µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/application"
compose-gotify-1  | 2024-01-21T13:45:20Z | 200 |     369.182µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/message?limit=100&since=0"
compose-gotify-1  | 2024-01-21T13:45:20Z | 200 |     203.545µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/application"
compose-gotify-1  | 2024-01-21T13:45:22Z | 200 |     390.526µs | 2a02:1808:4:76df:d865:4bff:fe05:c12a | GET      "/message?limit=100&since=0"
compose-gotify-1  | WebSocket: ReadError read tcp 172.18.0.5:80->192.168.0.118:53788: i/o timeout
compose-gotify-1  | 2024-01-21T13:51:32Z | 200 |    3.946554ms | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/stream?token=[masked]"
compose-gotify-1  | 2024-01-21T13:51:32Z | 200 |     432.669µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/message?limit=10"
compose-gotify-1  | 2024-01-21T13:52:30Z | 200 |     352.035µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/message?limit=10"
compose-gotify-1  | 2024-01-21T13:53:04Z | 200 |     378.769µs | 2a02:1811:b2be:ce00:7c56:3e29:c70d:d686 | GET      "/message?limit=10"
`

Android logs:
`2024-01-21 14:40:38.714 INFO: Entering LogsActivity
2024-01-21 14:40:34.840 ERROR: Error while api call: com.github.gotify.api.ApiException: Api Error
	at com.github.gotify.api.Callback$RetrofitCallback.onResponse(Callback.kt:35)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
2024-01-21 14:40:17.358 INFO: Entering LogsActivity
2024-01-21 14:02:25.986 INFO: Entering LogsActivity
2024-01-21 14:02:20.648 INFO: Entering LoginActivity
2024-01-21 14:02:17.052 INFO: Entering LogsActivity
2024-01-21 14:02:17.015 INFO: GotifyApplication: onCreate`

**Comment by jmattheis** [comment]
It looks like a wrongly typed username / password. Other things seem unlikely if it just works now.
