### ISSUE TITLE
App constantly disconnects with EOFException at WebSocketReader.readHeader

### ISSUE THREAD

**Issue by allista** [gotify/android#360]
Because of this the notifications never arrive when they are sent, and the only notification I get from time to time is "N missed while was disconnected".

## Setup

Server: docker, V2.4.0
Client: V2.7.1
Rev.proxy: Nginx Proxy Manager
Configuration: includes proxy read and other timeouts long enough (7d), no buffering.

The full stack trace from logs below:

```
2024-06-25 22:47:46.537 INFO: WebSocket(1144): opened
2024-06-25 22:47:46.441 INFO: WebSocket(1144): starting...
2024-06-25 22:47:33.768 INFO: Entering LogsActivity
2024-06-25 22:46:46.432 INFO: WebSocket: scheduling a restart in 60 second(s) (via alarm manager)
2024-06-25 22:46:46.425 ERROR: WebSocket(1143): failure  Message: : java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
2024-06-25 22:46:16.430 INFO: WebSocket(1143): opened
```

The timing does look like a 30s timeout...

**Comment by jmattheis** [comment]
show the gotify/server log

**Comment by allista** [comment]
Here's relevant entries from `gotify/server`

```
gotify  | 2024-06-25T22:46:14+03:00 | 200 |    7.771865ms |   192.168.0.143 | GET      "/stream?token=[masked]"
gotify  | 2024-06-25T22:46:14+03:00 | 200 |     1.02769ms |   192.168.0.143 | GET      "/message?limit=10"
gotify  | 2024-06-25T22:46:25+03:00 | 200 |     966.045µs |   192.168.0.237 | GET      "/stream?token=[masked]"
gotify  | WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
gotify  | WebSocket: ReadError websocket: close 1006 (abnormal closure): unexpected EOF
```

Don't see anything in nginx error log.

**Comment by jmattheis** [comment]
Does the webapp work, or does it also display an error message in the bottom left corner after some time?

It's very likely a misconfigured nginx proxy manager, please show your config from there.

**Comment by allista** [comment]
The webapp also displays the message abou WebSocket disconnect!

```
WebSocket connection closed, trying again in 30 seconds.
```

Nginx config, as far as I could stitch it together from `include` directives:

```nginx
# run nginx in foreground
daemon off;
pid /run/nginx/nginx.pid;
user npm;

# Set number of worker processes automatically based on number of CPU cores.
worker_processes auto;

# Enables the use of JIT for regular expressions to speed-up their processing.
pcre_jit on;

error_log /data/logs/fallback_error.log warn;

# Includes files with directives to load dynamic modules.
include /etc/nginx/modules/*.conf;

http {
  include                       /etc/nginx/mime.types;
  default_type                  application/octet-stream;
  sendfile                      on;
  server_tokens                 off;
  tcp_nopush                    on;
  tcp_nodelay                   on;
  client_body_temp_path         /tmp/nginx/body 1 2;
  keepalive_timeout             90s;
  proxy_connect_timeout         90s;
  proxy_send_timeout            90s;
  proxy_read_timeout            90s;
  ssl_prefer_server_ciphers     on;
  gzip                          on;
  proxy_ignore_client_abort     off;
  client_max_body_size          2000m;
  server_names_hash_bucket_size 1024;
  proxy_http_version            1.1;
  proxy_set_header              X-Forwarded-Scheme $scheme;
  proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header              Accept-Encoding "";
  proxy_cache                   off;
  proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
  proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;

  log_format proxy '[$time_local] $upstream_cache_status $upstream_status $status - $request_method $scheme $host "$request_uri" [Client $remote_addr] [Length $body_bytes_sent] [Gzip $gzip_ratio] [Sent-to $server] "$http_user_agent" "$http_referer"';
  log_format standard '[$time_local] $status - $request_method $scheme $host "$request_uri" [Client $remote_addr] [Length $body_bytes_sent] [Gzip $gzip_ratio] "$http_user_agent" "$http_referer"';

  access_log /data/logs/fallback_access.log proxy;

  # Dynamically generated resolvers file
  include /etc/nginx/conf.d/include/resolvers.conf;

  # Default upstream scheme
  map $host $forward_scheme {
          default http;
  }

  # Real IP Determination

  # Local subnets:
  set_real_ip_from 10.0.0.0/8;
  set_real_ip_from 172.16.0.0/12; # Includes Docker subnet
  set_real_ip_from 192.168.0.0/16;
  
  # NPM generated CDN ip ranges:
  include conf.d/include/ip_ranges.conf;
  
  # always put the following 2 lines after ip subnets:
  real_ip_header X-Real-IP;
  real_ip_recursive on;

  # Generated by NPM
  server {
    set $forward_scheme http;
    set $server         "gotify";
    set $port           80;

    listen 80;
    listen [::]:80;

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    
    server_name my.server.org;

    # Custom SSL
    ssl_certificate /data/custom_ssl/npm-3/fullchain.pem;
    ssl_certificate_key /data/custom_ssl/npm-3/privkey.pem;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
    add_header Strict-Transport-Security "max-age=63072000; preload" always;

    # Force SSL
    if ($scheme = "http") {
      return 301 https://$host$request_uri;
    }

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    access_log /data/logs/proxy-host-17_access.log proxy;
    error_log /data/logs/proxy-host-17_error.log warn;

    proxy_connect_timeout  1d;
    proxy_read_timeout  1d;
    proxy_send_timeout  1d;
    send_timeout  1d;
    proxy_buffering off;

    location / {
      # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
      add_header Strict-Transport-Security "max-age=63072000; preload" always;
      
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
      proxy_http_version 1.1;
      

      # Proxy!
      add_header       X-Served-By $host;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Scheme $scheme;
      proxy_set_header X-Forwarded-Proto  $scheme;
      proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP          $remote_addr;
      proxy_pass       $forward_scheme://$server:$port$request_uri;
    }
  }
}
```

**Comment by jmattheis** [comment]
Hmm looks okay at first glance, do you have anything else running between your gotify and the browser / android app like cloudflare tunnel etc?

**Comment by allista** [comment]
Oh boy :facepalm:

Indeed, I also have HAProxy on the gateway to proxy everything into internal network.
And the backend configured for NPM lacked the `timeout tunnel 1h` option, as per [their docs](https://www.haproxy.com/documentation/haproxy-configuration-tutorials/load-balancing/websocket/)

After adding the tunnel timeout, connection seems stable.

I'm sorry for bothering and for missing this stupidly obvious thing.

Hope this will help someone in the future, though.
